version: "3.7"

services:
    # image project
    app:
        container_name: ocr-app
        build:
            context: .
            dockerfile: Dockerfile
        image: ocr
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - ocr

    # nginx
    nginx:
        container_name: ocr-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - ocr

networks:
    ocr:
        driver: bridge
